language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

before_install:
  - gem update --system # Need for Ruby 2.5.0. https://github.com/travis-ci/travis-ci/issues/8978
  - gem update bundler

env:
  matrix:
    - SPROCKETS_VERSION="~> 2.2.0"
    - SPROCKETS_VERSION="~> 2.12.0"
    - SPROCKETS_VERSION="~> 3.0.0"
    - SPROCKETS_VERSION="~> 3.1.0"
    - SPROCKETS_VERSION="~> 3.2.0"
    - SPROCKETS_VERSION="~> 3.3.0"
    - SPROCKETS_VERSION="~> 3.4.0"
    - SPROCKETS_VERSION="~> 3.5.0"
    - SPROCKETS_VERSION="~> 3.6.0"
    - SPROCKETS_VERSION="~> 3.7.0"
    - SPROCKETS_VERSION="~> 4.0.0.beta4"
