language: ruby
cache: bundler
sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2

env:
  matrix:
    - SPROCKETS_VERSION="~> 2.1.0"
    - SPROCKETS_VERSION="~> 2.12.0"
    - SPROCKETS_VERSION="~> 3.0.0"
    - SPROCKETS_VERSION="~> 3.1.0"
